title: Md. Sawrab
url: "https://md-sawrab.github.io"
# baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "index"
 - name: "Education"
   link: "education"
 - name: "Experience"
   link: "experience"
 - name: "Others"
   link: "others"
